config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  resources :recipes do 
    resources :reviews 
  end
  

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :steps, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  default_scope -> { order(created_at: :desc) } #sets default order of recipes retrieved in db (newest to oldest)

  accepts_nested_attributes_for :recipe_ingredients, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :steps, :reject_if => :all_blank, :allow_destroy => true


  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 120}
  validates :description, presence: true, length: {maximum: 260}
  
  
  has_attached_file :recipe_img, styles: { recipe_index: "250x350>", recipe_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :recipe_img, content_type: /\Aimage\/.*\z/

  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :logged_in_user
    before_action :correct_user, only: [:edit, :update, :destroy]

    def index 
        @recipes = Recipe.paginate(page: params[:page])
    end

    def show 
        @recipe = Recipe.find(params[:id])
        if @recipe.reviews.blank?
			@average_review = 0
		else
			@average_review = @recipe.reviews.average(:rating).round(2)
		end
    end 

    def new
        @recipe = Recipe.new
        @recipe.recipe_ingredients.build.build_ingredient
    end



    def create 
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save 
            flash[:success] = "Recipe created"
            redirect_to @recipe
        else
            render 'new'
            # @slime_recipes = []
            # current_user.slimes.paginate(page: params[:page])
            # render 'static_pages/home'
        end
    end

    def edit 
    end

    def update
        if @recipe.update(recipe_params)
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end


    def destroy
        @recipe.destroy 
        flash[:success] = "slime deleted"
        redirect_to root_url 
    end

    

    private 

    def recipe_params 
        params.require(:recipe).permit(:title, :description, :recipe_img, 
            recipe_ingredients_attributes: [:id, :ingredient_name, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end 

    def correct_user 
        @recipe = current_user.recipes.find_by(id: params[:id])
        redirect_to root_url if @recipe.nil?
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <div class="control">
      <%= f.text_field :name, placeholder: "Ingredient" %>
      
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="row">
<li id="recipe-<%= recipe.id %> ">
<%= image_tag recipe.recipe_img.url(:recipe_index), class: "recipe" %></a>

<span class="user"><%= link_to recipe.user.name, recipe.user %></span>
<h4> <%= link_to recipe.title, recipe_path(recipe) %></h4>


<span class="timestamp">
Posted <%= time_ago_in_words(recipe.created_at) %> ago 
<% if current_user?(recipe.user) %>
<%= link_to "delete", recipe, method: :delete, data: { confirm: "You sure?"} %>
<% end %>
</span>
</li>
</div>

app/views/recipes/_recipe_form.html.erb
<%= form_with(model: @recipe, local: true) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="field">
<h1>Slime Name: </h1>
<%= f.text_area :title %>
<%= f.text_area :description, placeholder: "Add a short description about your recipe" %>
<%= f.file_field :recipe_img %>
</div>


<h3> Add Ingredients </h3>
<%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
<%= render 'recipe_ingredient_fields', f: recipe_ingredient %>
<% end %>

<div class="links">
<%= link_to_add_association 'Add Ingredient', f, :recipe_ingredients %>

<h3> Add Steps </h3>
<%= f.fields_for :steps do |step| %>
<%= render 'step_fields', f: step %>
<% end %>

<div class="links">
<%= link_to_add_association 'Add Steps', f, :steps %>


</div>

<%= f.submit "Post", class: "btn-cutstom2" %>


<% end %>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields field">
    <div class="field has-addons">
      
     <div class="field">  
 <%= f.text_field :ingredient_name, placeholder: "Ingredient" %> 
 <%= link_to_remove_association "remove ingredient", f %>  
 
  </div>
  </div>
</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
	<div class="field">
    <%= f.text_field :direction, placeholder: "Instructions" %>



		<%= link_to_remove_association "Remove Step", f %>
	</div><!-- field -->
</div><!-- nested fields-->

app/views/recipes/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="edit-recipe-form">
<h1> Edit Recipe </h1>
<%= render 'recipe_form' %>



</div>
</div>

app/views/recipes/index.html.erb
<h1>All Slime Recipes </h1>

<%= will_paginate %>
<ul class="recipe">
<%= render @recipes %>
</ul>
</div>
<%= will_paginate %>

app/views/recipes/new.html.erb
<div class="new-recipe-form">
<%= render 'recipe_form' %>

app/views/recipes/show.html.erb
<div class="col-md-4">
    <%= image_tag @recipe.recipe_img.url(:recipe_show), class: "recipe-show" %>
</div>

<div class="col-md-8">
<div class="recipe-info">
    <h1 class="recipe-title"> <%= @recipe.title %> </h1>
	<h2>posted by: <%= @recipe.user.name %> </h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
    <span class="number-of-reviews"> Based on <%=@recipe.reviews.count %> reviews </span>

    <p class="recipe-desc"> <%= @recipe.description %> </p>
    <p>
  
<h1>Ingredients: </h1>
<ul>
    <% @recipe.recipe_ingredients.each do |i| %>
        <li><%= i.ingredient_name %></li>
  <% end %>
</ul>

<h1>Steps </h1>
<% @recipe.steps.each do |s| %>
    <li><%= s.direction %></li>
  <% end %>
        
</div>

<div class="row">

	<div class="col-md-4">
    <div class="reviews">
<!-- Where the reviews/ratings will go -->
<h1>Reviews</h1>
    <%= render @recipe.reviews %>
        <div>
            <%= link_to "Add Review", new_recipe_review_path(@recipe), class: "btn btn-custom" %>

</div>
        </div>

    </div>	

</div>

<% if @recipe.user_id == current_user.id %>

<%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-custom"  %>
<%= link_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom"  %>

<% end %>


</div>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>