config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  resources :recipes do 
    resources :reviews 
  end
  

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation" >
<div class="alert alert-danger">
The form contains <%= pluralize(object.errors.count, "error")%>
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li> <%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_slimes.html.erb
<% if @slime_recipes.any? %>
<ol class="recipes">
<h1> Your Slimes</h1>
<%= render @slime_recipes %>
<% else %>
<div class="recipes">
<div class="center">
<h4>you don't have any slimes to display</h4>
<p>once you create a new slime recipe it will displayed here!</p>
<%= link_to "create a new slime recipe!", new_recipe_path, class: "btn btn-lg btn-primary" %></div>
</ol>
</div>





<%= will_paginate @slime_recipes,
    params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.recipes.count, "slime recipe") %></span>