config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  resources :recipes do 
    resources :reviews 
  end
  

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :logged_in_user
    before_action :find_recipe
    before_action :find_review, only: [:edit, :update, :destroy]

    def new 
        @review = Review.new 
    end

    def create 
        @review = Review.new(review_params)
        @review.recipe_id = @recipe.id 
        @review.user_id = current_user.id 
        if @review.save 
            redirect_to recipe_path(@recipe)
        else
            render 'new'
        end
    end

    def edit 
    end


    def update 
        if @review.update(review_params)
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end


    def destroy 
        @review.destroy 
        redirect_to recipe_path(@recipe)
    end

    private 

    def review_params 
        params.require(:review).permit(:rating, :comment)
    end

    def find_recipe 
        @recipe = Recipe.find(params[:recipe_id])
    end

    def find_review 
        @review = Review.find(params[:id])
    end


end

app/views/reviews/_review.html.erb
<div class="review">

<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"> <%= review.comment %></p>
<p> <%= review.user.name %></p>


    <% if review.user_id == current_user.id %>

    <div class="links btn-group">

    <%= link_to "Edit", edit_recipe_review_path(review.recipe, review), class: "btn btn-custom"%>
    <%= link_to "Delete", recipe_review_path(review.recipe, review), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-custom"  %>

</div>
    <% end %>


</div>

app/views/reviews/_review_form.html.erb
<%= form_with(model: @review, url: [@recipe, @review], local: true) do |f| %>
<%= render 'shared/error_messages', object: f.object %>


    <div id="rating-form">
    <label>Rating</label>
    </div>
    <%= f.text_field :comment %>
    <%= f.submit "Post", class: "btn-cutstom2" %>
<% end %>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="edit-review-form">
<h1> Edit review </h1>
<%= render 'review_form' %>



</div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="new-review-form">


<h1> New Review </h1>

<%= render 'review_form' %>

</div>
</div>