config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  resources :recipes do 
    resources :reviews 
  end
  

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
  <div class="navbar-header">
  <%= link_to "Slime Social", root_path, class: "navbar-brand" %>
  </div>
  
  
  
  <ul class="nav navbar-nav navbar-right">
  <li><%= link_to "Home", root_path %></li>

<% if logged_in? %>
<li> <%= link_to "Slimes", recipes_path %></li>
<li> <%= link_to "Users", users_path %></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account <b class="caret"></b>
</a>


<ul class="dropdown-menu">
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>
<li class="divider"></li>
<li>
<%= link_to "Log out", logout_path, method: "delete" %>
</li>
</ul>
</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>

  </ul>
  </nav>
  </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlimeSocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <div class="container">
  <% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert-alert-#{message_type}") %>
  <% end %>
    <%= yield %>
    </div>
  </body>
</html>